# Generated by Django 5.1.2 on 2024-10-31 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.IntegerField()),
                ('nome', models.CharField(max_length=150)),
                ('crm', models.CharField(max_length=6)),
                ('crm_estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11)),
                ('funcao', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('empresa', models.CharField(max_length=200)),
                ('cnpj_empresa', models.CharField(max_length=14)),
                ('data_agendamento', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ASO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=150)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=7)),
                ('id_medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.medico')),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.paciente')),
            ],
        ),
    ]
