# Generated by Django 5.1.2 on 2024-11-01 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aso',
            name='id_medico',
        ),
        migrations.RemoveField(
            model_name='aso',
            name='id_paciente',
        ),
        migrations.AddField(
            model_name='aso',
            name='cod',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paciente',
            name='id_aso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.aso'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='id_medico',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='app.medico'),
            preserve_default=False,
        ),
    ]
