# Generated by Django 5.1.2 on 2024-11-01 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_aso_id_medico_remove_aso_id_paciente_aso_cod_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aso',
            name='cod',
        ),
    ]
