# Generated by Django 5.1.2 on 2024-12-02 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_aso_cod'),
    ]

    operations = [
        migrations.CreateModel(
            name='index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Agendamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_agendamento', models.DateTimeField(auto_now_add=True)),
                ('id_aso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.aso')),
                ('id_medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.medico')),
            ],
        ),
    ]
