# Generated by Django 5.1.2 on 2024-12-06 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_index_login_agendamentos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='data_agendamento',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='id_aso',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='id_medico',
        ),
    ]
