# Generated by Django 5.1.2 on 2024-12-06 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_paciente_data_agendamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamentos',
            name='id_paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.paciente'),
        ),
    ]
