# Generated by Django 5.1.2 on 2024-12-06 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_agendamentos_id_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamentos',
            name='data_agendamento',
            field=models.DateTimeField(),
        ),
    ]
