# Generated by Django 5.1.2 on 2024-12-12 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_agendamentos_data_agendamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='agendarAso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='agendamentos',
            name='id_aso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.aso'),
        ),
    ]
