# Generated by Django 5.1.2 on 2024-12-15 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_agendaraso_alter_agendamentos_id_aso'),
    ]

    operations = [
        migrations.CreateModel(
            name='cadastrarMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='medico',
            name='cod',
        ),
    ]
